# Generated by Django 5.2 on 2025-05-19 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.CharField(choices=[('smallest_balance', 'Smallest Balance'), ('highest_interest', 'Highest Interest'), ('fewest_payments', 'Fewest Payments')], default='smallest_balance', max_length=30)),
                ('extra_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('months_to_freedom', models.IntegerField()),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_summary', models.TextField(blank=True)),
                ('loan_data', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
