# Generated by Django 5.2 on 2025-05-20 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year_of_retirement', models.IntegerField()),
                ('init_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_growth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yield_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('projected_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
