# Generated by Django 4.2.21 on 2025-05-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='team',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
