# Generated by Django 5.2 on 2025-05-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_retirementcalculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retirementcalculation',
            old_name='year_of_retirement',
            new_name='retirement_age',
        ),
        migrations.RemoveField(
            model_name='retirementcalculation',
            name='match',
        ),
        migrations.RemoveField(
            model_name='retirementcalculation',
            name='salary_growth',
        ),
        migrations.RemoveField(
            model_name='retirementcalculation',
            name='yield_rate',
        ),
        migrations.AddField(
            model_name='retirementcalculation',
            name='current_age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retirementcalculation',
            name='init_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='retirementcalculation',
            name='projected_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='retirementcalculation',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
