# Generated by Django 4.2.21 on 2025-05-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_year_of_retirement_retirementcalculation_retirement_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementcalculation',
            name='total_employee_contrib',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retirementcalculation',
            name='total_employer_contrib',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
