# Generated by Django 4.2.21 on 2025-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtcalculation',
            name='additional_payment',
        ),
        migrations.RemoveField(
            model_name='debtcalculation',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='debtcalculation',
            name='monthly_payment',
        ),
        migrations.AddField(
            model_name='debtcalculation',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtcalculation',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtcalculation',
            name='months_to_freedom',
            field=models.IntegerField(),
        ),
    ]
