# Generated by Django 4.2.21 on 2025-05-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_debtcalculation_additional_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtcalculation',
            name='loan_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
