# Generated by Django 4.2.21 on 2025-05-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_debtcalculation_loan_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtcalculation',
            name='extra_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtcalculation',
            name='strategy',
            field=models.CharField(choices=[('smallest_balance', 'Smallest Balance'), ('highest_interest', 'Highest Interest'), ('fewest_payments', 'Fewest Payments')], default='smallest_balance', max_length=30),
        ),
        migrations.AddField(
            model_name='debtcalculation',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debtcalculation',
            name='loan_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='debtcalculation',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtcalculation',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
