# Generated by Django 4.2.21 on 2025-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_debtcalculation_extra_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtcalculation',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
